# SPDX-License-Identifier: AGPL-3.0-only
# Route ALL name resolution through the local dnsmasq (127.0.0.1:5353) so every lookup
# of api.anthropic.com passes the nftset path and lands its IP in the allowlist before
# the agent connects. systemd-resolved keeps its 127.0.0.53:53 stub for the agents;
# dnsmasq is the sole upstream. No fallback -> no allowlist bypass.
[Resolve]
DNS=127.0.0.1:5353
Domains=~.
FallbackDNS=
