# SPDX-License-Identifier: AGPL-3.0-only
# Bare-metal tpm2 production override (ADR-0034 inc2, build-time, BULKHEAD_SEAL_KEY=tpm2). Installed
# as bulkhead-egress-proxy.service.d/30-mitm-cred-tpm2.conf only in a tpm2 build (sorts AFTER both the
# 20-mitm.conf base mitm drop-in and the generic 20-audit-cred-tpm2.conf). Switches the re-signing CA
# KEY from plaintext-on-/data (LoadCredential) to the TPM2-sealed cred (LoadCredentialEncrypted) the
# provision service produced; the public ca.crt stays plaintext (it is not secret).
#   - LoadCredential= (empty) RESETS the LoadCredential list, which at this point holds the plaintext
#     mitm-ca-key + mitm-ca-crt from 20-mitm.conf. The audit-seed was already moved to
#     LoadCredentialEncrypted by 20-audit-cred-tpm2.conf, so it is NOT in this list and is untouched.
#   - re-add the public cert (LoadCredential) + the sealed key (LoadCredentialEncrypted), landing both
#     at the SAME $CREDENTIALS_DIRECTORY/mitm-ca-{crt,key} paths loadMITMCA reads — ZERO Go change.
# systemd refuses to start if the sealed key won't decrypt (fail-closed, reinforcing REQUIRE_MITM_CA=1).
# Not installed in the default plain (VM/dev) build.
[Service]
LoadCredential=
LoadCredential=mitm-ca-crt:/data/bulkhead/mitm-ca/ca.crt
LoadCredentialEncrypted=mitm-ca-key:/data/bulkhead/mitm-ca/ca.key.cred
