# SPDX-License-Identifier: AGPL-3.0-only
# Bare-metal tpm2 production override (ADR-0034 inc2, build-time, BULKHEAD_SEAL_KEY=tpm2). Installed
# as bulkhead-provision-mitm-ca.service.d/20-tpm2.conf only in a tpm2 build. Sets the seal mode so the
# first-boot CA provision TPM2-SEALS ca.key -> ca.key.cred (systemd-creds --with-key=tpm2
# --tpm2-pcrs=7) and persists NO plaintext key, instead of writing a plaintext ca.key. Pair with
# mitm-cred-tpm2.conf on the proxy. Not installed in the default plain (VM/dev) build, so that path
# stays byte-for-byte unchanged. qemu's vTPM sealing is unreliable (ADR-0001 #12), so plain is the VM
# default and this is the bare-metal posture — same as the audit seed (seal-tpm2-mode.conf).
[Service]
Environment=BULKHEAD_SEAL_KEY=tpm2
