# SPDX-License-Identifier: AGPL-3.0-only
# Bare-metal tpm2 production override (ADR-0028, build-time, BULKHEAD_SEAL_KEY=tpm2). Installed as
# bulkhead-seal-audit-key.service.d/20-tpm2.conf only in a tpm2 build. Overrides the base unit's
# Environment=BULKHEAD_SEAL_KEY=plain (Environment= is keyed: the later drop-in value wins), so the
# first-boot seal provisions a TPM2-SEALED /data/bulkhead/audit-seed.cred (systemd-creds
# --with-key=tpm2 --tpm2-pcrs=7) instead of a plaintext seed. Pair with audit-cred-tpm2.conf on the
# consumers. Not installed in the default plain (VM/dev) build.
[Service]
Environment=BULKHEAD_SEAL_KEY=tpm2
