# SPDX-License-Identifier: AGPL-3.0-only
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "bulkhead"
BBFILE_PATTERN_bulkhead = "^${LAYERDIR}/"
BBFILE_PRIORITY_bulkhead = "10"

LAYERDEPENDS_bulkhead = "core openembedded-layer rauc"
LAYERSERIES_COMPAT_bulkhead = "scarthgap"
